server:
  port: ${service.port}

spring:
  config:
    import:
      - secrets.yml

  datasource:
    url: jdbc:postgresql://localhost:5434/${postgres.db:goodday_dispatch} #local
#    url: jdbc:postgresql://gd_dispatch_db:5432/${postgres.db} #docker - 서비스 자체를 띄울 때 사용
    driver-class-name: org.postgresql.Driver
    username: ${postgres.user:dispatch}
    password: ${postgres.password:dispatch1234}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false #타임아웃 스케줄러 쿼리문이 너무 많이 나와서 임시로 false

  data:
    redis:
      host: localhost
      port: ${redis.port:6379}

  kafka:
    bootstrap-servers: localhost:${kafka.port} #local
#    bootstrap-servers: kafka:${kafka.port} # docker - 서비스 자체를 띄울 때 사용

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.port:8761}/eureka/ #local
#      defaultZone: http://server:${eureka.port}/eureka/ # docker - 서비스 자체를 띄울 때 사용


management:
  zipkin:
    tracing:
      endpoint: "http://localhost:${zipkin.port:9411}/api/v2/spans"

logging:
  level:
    com.gooddaytaxi.support: DEBUG # INFO, DEBUG, WARN, ERROR