version: "3.8"

services:

  # ============================
  # POSTGRES — 서비스별 DB
  # ============================

  account-db:
    image: postgres:15
    container_name: gd_account_db
    environment:
      POSTGRES_USER: ${ACCOUNT_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASS}
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - account_pgdata:/var/lib/postgresql/data
    networks:
      - gd-network

  dispatch-db:
    image: postgres:15
    container_name: gd_dispatch_db
    environment:
      POSTGRES_USER: ${DISPATCH_DB_USER}
      POSTGRES_PASSWORD: ${DISPATCH_DB_PASS}
      POSTGRES_DB: ${DISPATCH_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - dispatch_pgdata:/var/lib/postgresql/data
    networks:
      - gd-network

  trip-db:
    image: postgres:15
    container_name: gd_trip_db
    environment:
      POSTGRES_USER: ${TRIP_DB_USER}
      POSTGRES_PASSWORD: ${TRIP_DB_PASS}
      POSTGRES_DB: ${TRIP_DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - trip_pgdata:/var/lib/postgresql/data
    networks:
      - gd-network

  payment-db:
    image: postgres:15
    container_name: gd_payment_db
    environment:
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASS}
      POSTGRES_DB: ${PAYMENT_DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data
    networks:
      - gd-network

  support-db:
    image: postgres:15
    container_name: gd_support_db
    environment:
      POSTGRES_USER: ${SUPPORT_DB_USER}
      POSTGRES_PASSWORD: ${SUPPORT_DB_PASS}
      POSTGRES_DB: ${SUPPORT_DB_NAME}
    ports:
      - "5437:5432"
    volumes:
      - support_pgdata:/var/lib/postgresql/data
    networks:
      - gd-network


  # ============================
  # REDIS
  # ============================

  redis:
    image: redis:7
    container_name: gd_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - gd-network

  # ============================
  # ZIPKIN
  # ============================

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: gd_zipkin
    ports:
      - "${ZIPKIN_PORT}:9411"
    networks:
      - gd-network

   # ============================
   # KAFKA
   # ============================

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: gd_zookeeper
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    container_name: gd_kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${KAFKA_EXTERNAL_HOST}:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./kafka-init:/docker-entrypoint-init.d:ro

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: gd_kafka-ui
    volumes:
      - kafka-ui-data:/var/lib/kafka-ui
    depends_on:
      - kafka
    ports:
      - "9999:9999"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_READONLY: "false"
      SERVER_PORT: 9999


  # ============================
  # CORE SERVICES - 게이트웨이와 서버 완성 후 주석 해제
  # ============================
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: gd_eureka
    ports:
      - "${EUREKA_PORT}:8761"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - gd-network

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gd_gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      ZIPKIN_BASE_URL: http://zipkin:9411
    depends_on:
      - server
    networks:
      - gd-network


  # # ============================
  # # DOMAIN SERVICES
  # # ============================

  # account-service:
  #   build: ./account-service
  #   container_name: gd_account_service
  #   ports:
  #     - "${ACCOUNT_SERVICE_PORT}:8080"
  #   depends_on:
  #     - account-db
  #     - server
  #   networks:
  #     - gd-network

  # dispatch-service:
  #   build: ./dispatch-service
  #   container_name: gd_dispatch_service
  #   ports:
  #     - "${DISPATCH_SERVICE_PORT}:8080"
  #   depends_on:
  #     - dispatch-db
  #     - kafka
  #     - server
  #   networks:
  #     - gd-network

  # trip-service:
  #   build: ./trip-service
  #   container_name: gd_trip_service
  #   ports:
  #     - "${TRIP_SERVICE_PORT}:8080"
  #   depends_on:
  #     - trip-db
  #     - server
  #   networks:
  #     - gd-network

  # payment-service:
  #   build: ./payment-service
  #   container_name: gd_payment_service
  #   ports:
  #     - "${PAYMENT_SERVICE_PORT}:8080"
  #   depends_on:
  #     - payment-db
  #     - kafka
  #     - server
  #   networks:
  #     - gd-network

  # support-service:
  #   build: ./support-service
  #   container_name: gd_support_service
  #   ports:
  #     - "${SUPPORT_SERVICE_PORT}:8080"
  #   depends_on:
  #     - support-db
  #     - server
  #   networks:
  #     - gd-network


volumes:
  account_pgdata:
  dispatch_pgdata:
  trip_pgdata:
  payment_pgdata:
  support_pgdata:
  kafka-data:
  zookeeper-data:
  kafka-ui-data:

networks:
  gd-network:
