global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

scrape_configs:

  # ========================
  # GATEWAY
  # ========================
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Docker 컨테이너
      - targets: ['gd_gateway:8080']
      # 로컬 개발
      - targets: ['host.docker.internal:8080']


  # ========================
  # ACCOUNT SERVICE
  # ========================
  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Docker 컨테이너
      - targets: ['gd_account_service:8080']
      # 로컬 개발
      - targets: ['host.docker.internal:8201']


  # ========================
  # DISPATCH SERVICE
  # ========================
  - job_name: 'dispatch-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Docker 컨테이너
      - targets: ['gd_dispatch_service:8080']
      # 로컬 개발
      - targets: ['host.docker.internal:8202']


  # ========================
  # TRIP SERVICE
  # ========================
  - job_name: 'trip-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Docker 컨테이너
      - targets: ['gd_trip_service:8080']
      # 로컬 개발
      - targets: ['host.docker.internal:8203']


  # ========================
  # PAYMENT SERVICE
  # ========================
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Docker 컨테이너
      - targets: ['gd_payment_service:8080']
      # 로컬 개발
      - targets: ['host.docker.internal:8204']


  # ========================
  # SUPPORT SERVICE
  # ========================
  - job_name: 'support-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Docker 컨테이너
      - targets: ['gd_support_service:8080']
      # 로컬 개발
      - targets: ['host.docker.internal:8205']


  # ========================
  # Redis Monitoring
  # ========================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

