spring:
  config:
    import:
      - secrets.yaml
  application:
    name: server

server:
  port: ${service.port}

eureka:
  instance:
    hostname: gd_eureka                    # 도커 컨테이너명과 일치시킴
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://server:${service.port}/eureka/
