
server:
  port: ${SERVICE_PORT:8204}

spring:
  config:
    import:
      - secrets.yml

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:goodday_payment}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:payment}
    password: ${DB_PASSWORD:payment1234}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  data:
    redis:
      host: 10.2.0.28
      port: 6379
      database: 0

  kafka:
    bootstrap-servers: 10.2.0.226:9092
    consumer:
      group-id: dispatch-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true

kafka:
  topic:
    payment: payment-topic


eureka:
  client:
    service-url:
      defaultZone: http://10.1.0.61:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://:10.1.0.61:9411/api/v2/spans

logging:
  level:
    root: INFO
    com.gooddaytaxi: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF

payment:
  event:
    payload-version: 1

toss:
  secret-key: ${toss.test-secret-key}

