spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:goodday_payment}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:payment}
    password: ${DB_PASSWORD:payment1234}
    hikari:
      connection-init-sql: "SET lock_timeout TO '3s'"

  data:
    redis:
      host: ${REDIS_HOSTNAME:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  kafka:
    bootstrap-servers: ${KAFKA_HOSTNAME:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

server:
  port: ${PAYMENT_SERVICE_PORT:8204}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOSTNAME:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans

logging:
  level:
    root: INFO
    com.gooddaytaxi: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF

toss:
  secret-key: ${TOSS_SECRET_KEY:}
