server:
  port: ${TRIP_SERVICE_PORT:8203}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/${DB_NAME:goodday_trip}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:trip}
    password: ${DB_PASSWORD:trip1234}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false

  kafka:
    bootstrap-servers: ${KAFKA_HOSTNAME}:${KAFKA_PORT:9092}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:10.1.0.61}:${EUREKA_PORT:8761}/eureka/


management:
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOSTNAME:10.1.0.61}:${ZIPKIN_PORT:9411}/api/v2/spans"

logging:
  level:
    root: INFO
    com.gooddaytaxi: INFO
    # 프레임워크 소음 줄이기
    org.springframework: WARN
    org.hibernate: WARN
    # :white_check_mark: "쿼리문 내려오는" 거 끄기 (Hibernate SQL 로그)
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF   # 바인딩 값 로그(부트3/hibernate6)