server:
  port: ${DISPATCH_SERVICE_PORT:8083}

spring:
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:docker}
  application:
    name: dispatch-service

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT}/eureka/


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:${ZIPKIN_PORT}/api/v2/spans"