server:
  port: ${ACCOUNT_SERVICE_PORT:8201}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT:5433}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME}:${EUREKA_PORT:8761}/eureka/

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOSTNAME}:${ZIPKIN_PORT:9411}/api/v2/spans

logging:
  level:
    root: INFO
    com.gooddaytaxi: INFO
    # 프레임워크 소음 줄이기
    org.springframework: WARN
    org.hibernate: WARN
    # :white_check_mark: "쿼리문 내려오는" 거 끄기 (Hibernate SQL 로그)
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF   # 바인딩 값 로그(부트3/hibernate6)